
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.tvsa.soin.xmlns.secman.servicios.secmandascomerautenticar.ProcessResponse;
import com.tvsa.soin.xmlns.secman.servicios.secmandascomerautenticar.UserLogin;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "SecmanBsAutenticar", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
            com.tvsa.soin.xmlns.secman.servicios.secmandascomerautenticar.ObjectFactory.class,
            org.tempuri.ObjectFactory.class })
public interface SecmanBsAutenticar {


    /**
     *
     * @param userLogin
     * @return
     *     returns com.tvsa.soin.xmlns.secman.servicios.secmandascomerautenticar.ProcessResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "autenticarUsuario", targetNamespace = "http://tempuri.org/",
                    className = "org.tempuri.AutenticarUsuario")
    @ResponseWrapper(localName = "autenticarUsuarioResponse", targetNamespace = "http://tempuri.org/",
                     className = "org.tempuri.AutenticarUsuarioResponse")
    public ProcessResponse autenticarUsuario(@WebParam(name = "UserLogin", targetNamespace = "") UserLogin userLogin);

}
