
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.tvsa.soin.xmlns.secman.servicios.secmandascomerautenticar.ProcessResponse;
import com.tvsa.soin.xmlns.secman.servicios.secmaninfsendmail.Mail;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "SecmanDasEnviarCorreo", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
            com.tvsa.soin.xmlns.secman.servicios.secmandascomerautenticar.ObjectFactory.class,
            com.tvsa.soin.xmlns.secman.servicios.secmaninfsendmail.ObjectFactory.class, org.tempuri.ObjectFactory.class
    })
public interface SecmanDasEnviarCorreo {


    /**
     *
     * @param mail
     * @return
     *     returns com.tvsa.soin.xmlns.secman.servicios.secmandascomerautenticar.ProcessResponse
     */
    @WebMethod(operationName = "EnviarCorreo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "EnviarCorreo", targetNamespace = "http://tempuri.org/",
                    className = "org.tempuri.EnviarCorreo")
    @ResponseWrapper(localName = "EnviarCorreoResponse", targetNamespace = "http://tempuri.org/",
                     className = "org.tempuri.EnviarCorreoResponse")
    public ProcessResponse enviarCorreo(@WebParam(name = "mail", targetNamespace = "") Mail mail);

}
