
package mx.com.televisa.secman.view.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.tvsa.soin.xmlns.secman.servicios.usuariopermisos.PermisoOutputCollection;
import com.tvsa.soin.xmlns.secman.servicios.usuariopermisos.PermisosUsuarioInputParameters;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "SecmanDasUsuarioPermisos", targetNamespace = "http://webServices.view.secman.televisa.com.mx/")
@XmlSeeAlso({
            com.tvsa.soin.xmlns.secman.servicios.usuariopermisos.ObjectFactory.class,
            mx.com.televisa.secman.view.webservices.ObjectFactory.class })
public interface SecmanDasUsuarioPermisos {


    /**
     *
     * @param arg0
     * @return
     *     returns com.tvsa.soin.xmlns.secman.servicios.usuariopermisos.PermisoOutputCollection
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerRolTareaPermisos",
                    targetNamespace = "http://webServices.view.secman.televisa.com.mx/",
                    className = "mx.com.televisa.secman.view.webservices.ObtenerRolTareaPermisos")
    @ResponseWrapper(localName = "obtenerRolTareaPermisosResponse",
                     targetNamespace = "http://webServices.view.secman.televisa.com.mx/",
                     className = "mx.com.televisa.secman.view.webservices.ObtenerRolTareaPermisosResponse")
    public PermisoOutputCollection obtenerRolTareaPermisos(@WebParam(name = "arg0", targetNamespace = "")
                                                           PermisosUsuarioInputParameters arg0);

}
