package mx.com.televisa.secman.view.webservices;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1008
public class SecmanDasUsuarioPermisosPortClient {
    public static void main(String[] args) {
        SecmanDasUsuarioPermisosService secmanDasUsuarioPermisosService = new SecmanDasUsuarioPermisosService();
        SecmanDasUsuarioPermisos secmanDasUsuarioPermisos =
            secmanDasUsuarioPermisosService.getSecmanDasUsuarioPermisosPort();
        // Add your code to call the desired methods.


    }
}
