package com.televisa.integration.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 18 11:31:08 CDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EvetvIntServicesCatTabViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EvetvIntServicesCatTabViewImpl() {
    }
    
    
    @Override
    protected void executeQueryForCollection(Object toQc, Object[] taParams, int tiNumUserParams) {
        
        String lsWhere = "";
        if(getWhereClause() == null){
            AppModuleIntergrationImpl loAppMod = new AppModuleIntergrationImpl();
            String lsUsrVtaTrad = loAppMod.getValueSessionFromAttribute("RolUsrVtaTradicional");
            //System.out.println("Es usuario venta tradicional? ["+lsUsrVtaTrad+"]");
            if(lsUsrVtaTrad.equalsIgnoreCase("true")){
                lsWhere = "NOM_SERVICE = 'WsVentaTradicionalUsr'";
            }else{
                lsWhere = " 1 = 1 ";            
            }
            
        }
        else{
            lsWhere = getWhereClause();
        }
        //System.out.println("WHERE: "+lsWhere);
        setWhereClause(lsWhere);
        super.executeQueryForCollection(toQc, taParams, tiNumUserParams);
    }
}

