package com.televisa.integration.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 11 18:35:58 CDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EvetvIntServicesParamsTabViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EvetvIntServicesParamsTabViewImpl() {
    }
}

