package com.televisa.integration.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 28 19:54:34 CDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EvetvIntServiceBitacoraTabViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EvetvIntServiceBitacoraTabViewImpl() {
    }
}

