package com.televisa.integration.model;

import java.sql.Blob;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 29 11:12:22 CST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EvetvIntXmlFilesTabViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_EVETVINTXMLFILESTAB = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdFileXml,
        IdRequest,
        IdService,
        NomFile,
        IndFileType,
        IndServiceType,
        IndFileStream,
        IndEstatus,
        FecCreationDate,
        NomUserName;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDFILEXML = AttributesEnum.IdFileXml.index();
    public static final int IDREQUEST = AttributesEnum.IdRequest.index();
    public static final int IDSERVICE = AttributesEnum.IdService.index();
    public static final int NOMFILE = AttributesEnum.NomFile.index();
    public static final int INDFILETYPE = AttributesEnum.IndFileType.index();
    public static final int INDSERVICETYPE = AttributesEnum.IndServiceType.index();
    public static final int INDFILESTREAM = AttributesEnum.IndFileStream.index();
    public static final int INDESTATUS = AttributesEnum.IndEstatus.index();
    public static final int FECCREATIONDATE = AttributesEnum.FecCreationDate.index();
    public static final int NOMUSERNAME = AttributesEnum.NomUserName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EvetvIntXmlFilesTabViewRowImpl() {
    }

    /**
     * Gets EvetvIntXmlFilesTab entity object.
     * @return the EvetvIntXmlFilesTab
     */
    public EntityImpl getEvetvIntXmlFilesTab() {
        return (EntityImpl) getEntity(ENTITY_EVETVINTXMLFILESTAB);
    }

    /**
     * Gets the attribute value for ID_FILE_XML using the alias name IdFileXml.
     * @return the ID_FILE_XML
     */
    public Integer getIdFileXml() {
        return (Integer) getAttributeInternal(IDFILEXML);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_FILE_XML using the alias name IdFileXml.
     * @param value value to set the ID_FILE_XML
     */
    public void setIdFileXml(Integer value) {
        setAttributeInternal(IDFILEXML, value);
    }

    /**
     * Gets the attribute value for ID_REQUEST using the alias name IdRequest.
     * @return the ID_REQUEST
     */
    public Integer getIdRequest() {
        return (Integer) getAttributeInternal(IDREQUEST);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_REQUEST using the alias name IdRequest.
     * @param value value to set the ID_REQUEST
     */
    public void setIdRequest(Integer value) {
        setAttributeInternal(IDREQUEST, value);
    }

    /**
     * Gets the attribute value for ID_SERVICE using the alias name IdService.
     * @return the ID_SERVICE
     */
    public Integer getIdService() {
        return (Integer) getAttributeInternal(IDSERVICE);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_SERVICE using the alias name IdService.
     * @param value value to set the ID_SERVICE
     */
    public void setIdService(Integer value) {
        setAttributeInternal(IDSERVICE, value);
    }

    /**
     * Gets the attribute value for NOM_FILE using the alias name NomFile.
     * @return the NOM_FILE
     */
    public String getNomFile() {
        return (String) getAttributeInternal(NOMFILE);
    }

    /**
     * Sets <code>value</code> as attribute value for NOM_FILE using the alias name NomFile.
     * @param value value to set the NOM_FILE
     */
    public void setNomFile(String value) {
        setAttributeInternal(NOMFILE, value);
    }

    /**
     * Gets the attribute value for IND_FILE_TYPE using the alias name IndFileType.
     * @return the IND_FILE_TYPE
     */
    public String getIndFileType() {
        return (String) getAttributeInternal(INDFILETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_FILE_TYPE using the alias name IndFileType.
     * @param value value to set the IND_FILE_TYPE
     */
    public void setIndFileType(String value) {
        setAttributeInternal(INDFILETYPE, value);
    }

    /**
     * Gets the attribute value for IND_SERVICE_TYPE using the alias name IndServiceType.
     * @return the IND_SERVICE_TYPE
     */
    public String getIndServiceType() {
        return (String) getAttributeInternal(INDSERVICETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_SERVICE_TYPE using the alias name IndServiceType.
     * @param value value to set the IND_SERVICE_TYPE
     */
    public void setIndServiceType(String value) {
        setAttributeInternal(INDSERVICETYPE, value);
    }

    /**
     * Gets the attribute value for IND_FILE_STREAM using the alias name IndFileStream.
     * @return the IND_FILE_STREAM
     */
    public Blob getIndFileStream() {
        return (Blob) getAttributeInternal(INDFILESTREAM);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_FILE_STREAM using the alias name IndFileStream.
     * @param value value to set the IND_FILE_STREAM
     */
    public void setIndFileStream(Blob value) {
        setAttributeInternal(INDFILESTREAM, value);
    }

    /**
     * Gets the attribute value for IND_ESTATUS using the alias name IndEstatus.
     * @return the IND_ESTATUS
     */
    public String getIndEstatus() {
        return (String) getAttributeInternal(INDESTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for IND_ESTATUS using the alias name IndEstatus.
     * @param value value to set the IND_ESTATUS
     */
    public void setIndEstatus(String value) {
        setAttributeInternal(INDESTATUS, value);
    }

    /**
     * Gets the attribute value for FEC_CREATION_DATE using the alias name FecCreationDate.
     * @return the FEC_CREATION_DATE
     */
    public String getFecCreationDate() {
        return (String) getAttributeInternal(FECCREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FEC_CREATION_DATE using the alias name FecCreationDate.
     * @param value value to set the FEC_CREATION_DATE
     */
    public void setFecCreationDate(String value) {
        setAttributeInternal(FECCREATIONDATE, value);
    }

    /**
     * Gets the attribute value for NOM_USER_NAME using the alias name NomUserName.
     * @return the NOM_USER_NAME
     */
    public String getNomUserName() {
        return (String) getAttributeInternal(NOMUSERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NOM_USER_NAME using the alias name NomUserName.
     * @param value value to set the NOM_USER_NAME
     */
    public void setNomUserName(String value) {
        setAttributeInternal(NOMUSERNAME, value);
    }
}

