
package es.com.evendor;

import com.televisa.integration.view.front.util.UtilFaces;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Web Service de Evendor EveTv
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
/*@WebServiceClient(name = "WSNeptuno", targetNamespace = "http://evendor.com.es/",
                  wsdlLocation =
                  "http://10.7.15.178:8080/WSNeptuno.asmx?WSDL#%7Bhttp%3A%2F%2Fevendor.com.es%2F%7DWSNeptuno")*/
@WebServiceClient(name = "WSNeptuno", targetNamespace = "http://evendor.com.es/")
public class WSNeptuno extends Service {

    private final static URL WSNEPTUNO_WSDL_LOCATION;
    private final static WebServiceException WSNEPTUNO_EXCEPTION;
    private final static QName WSNEPTUNO_QNAME = new QName("http://evendor.com.es/", "WSNeptuno");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            String lsDynaUrl = new UtilFaces().getConfigParameterByName("WsNeptuno");
            url =
                new URL(lsDynaUrl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSNEPTUNO_WSDL_LOCATION = url;
        WSNEPTUNO_EXCEPTION = e;
    }

    public WSNeptuno() {
        super(__getWsdlLocation(), WSNEPTUNO_QNAME);
    }

    public WSNeptuno(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSNEPTUNO_QNAME, features);
    }

    public WSNeptuno(URL wsdlLocation) {
        super(wsdlLocation, WSNEPTUNO_QNAME);
    }

    public WSNeptuno(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSNEPTUNO_QNAME, features);
    }

    public WSNeptuno(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSNeptuno(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WSNeptunoSoap
     */
    @WebEndpoint(name = "WSNeptunoSoap")
    public WSNeptunoSoap getWSNeptunoSoap() {
        return super.getPort(new QName("http://evendor.com.es/", "WSNeptunoSoap"), WSNeptunoSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSNeptunoSoap
     */
    @WebEndpoint(name = "WSNeptunoSoap")
    public WSNeptunoSoap getWSNeptunoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://evendor.com.es/", "WSNeptunoSoap"), WSNeptunoSoap.class, features);
    }

    /**
     *
     * @return
     *     returns WSNeptunoSoap
     */
    @WebEndpoint(name = "WSNeptunoSoap12")
    public WSNeptunoSoap getWSNeptunoSoap12() {
        return super.getPort(new QName("http://evendor.com.es/", "WSNeptunoSoap12"), WSNeptunoSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSNeptunoSoap
     */
    @WebEndpoint(name = "WSNeptunoSoap12")
    public WSNeptunoSoap getWSNeptunoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://evendor.com.es/", "WSNeptunoSoap12"), WSNeptunoSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSNEPTUNO_EXCEPTION != null) {
            throw WSNEPTUNO_EXCEPTION;
        }
        return WSNEPTUNO_WSDL_LOCATION;
    }

}
