package mx.com.televisa.secman.view.permisos;

import javax.xml.ws.WebServiceRef;

import mx.com.televisa.secman.view.permisos.types.PermisoOutputCollection;
import mx.com.televisa.secman.view.permisos.types.PermisosUsuarioInputParameters;
import mx.com.televisa.secman.view.permisos.types.Usuario;

// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

public class SecmanDasUsuarioPermisosPortClient
{
  @WebServiceRef
  private static SecmanDasUsuarioPermisosService secmanDasUsuarioPermisosService;

  public static void main(String [] args)
  {
    secmanDasUsuarioPermisosService = new SecmanDasUsuarioPermisosService();
    SecmanDasUsuarioPermisos secmanDasUsuarioPermisos = secmanDasUsuarioPermisosService.getSecmanDasUsuarioPermisosPort();
    // Add your code to call the desired methods.
    PermisosUsuarioInputParameters uip = new PermisosUsuarioInputParameters();
      uip.setNomAplicacion("OrduniOnAir");
      uip.setUserName("lmercador");
      System.out.println("invocar ws permisos");
      try{
        PermisoOutputCollection poc = secmanDasUsuarioPermisos.obtenerRolTareaPermisos(uip);
        Usuario u = poc.getUsuario();
        System.out.println("idUsuario: "+u.getIdUsuario());
          
      }catch(Exception ex){
          System.out.println("ERROR "+ex.getMessage());
      }
  }
}
