package mx.com.televisa.secman.view.permisos;

import com.televisa.integration.view.front.util.UtilFaces;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)
/*
@WebServiceClient(wsdlLocation="http://tvmiddev1.televisa.net:8011/Secman/Proxy/SecmanDasPermisosUsuarioProxy?wsdl",
  targetNamespace="http://webServices.view.secman.televisa.com.mx/", name="SecmanDasUsuarioPermisosService")
*/
@WebServiceClient(targetNamespace="http://webServices.view.secman.televisa.com.mx/", name="SecmanDasUsuarioPermisosService")
public class SecmanDasUsuarioPermisosService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("mx.com.televisa.secman.view.permisos.SecmanDasUsuarioPermisosService");
      URL baseUrl = SecmanDasUsuarioPermisosService.class.getResource(".");
        String lsDynaUrl = new UtilFaces().getConfigParameterByName("WsSecmanPermissions");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            SecmanDasUsuarioPermisosService.class.getResource(lsDynaUrl);
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, lsDynaUrl);
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, lsDynaUrl);
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://tvmiddev1.televisa.net:8011/Secman/Proxy/SecmanDasPermisosUsuarioProxy?wsdl",
          e);
    }
  }

  public SecmanDasUsuarioPermisosService()
  {
    super(wsdlLocationURL,
          new QName("http://webServices.view.secman.televisa.com.mx/",
                    "SecmanDasUsuarioPermisosService"));
  }

  public SecmanDasUsuarioPermisosService(URL wsdlLocation,
                                         QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="SecmanDasUsuarioPermisosPort")
  public mx.com.televisa.secman.view.permisos.SecmanDasUsuarioPermisos getSecmanDasUsuarioPermisosPort()
  {
    return (mx.com.televisa.secman.view.permisos.SecmanDasUsuarioPermisos) super.getPort(new QName("http://webServices.view.secman.televisa.com.mx/",
                                                                                                               "SecmanDasUsuarioPermisosPort"),
                                                                                                     mx.com.televisa.secman.view.permisos.SecmanDasUsuarioPermisos.class);
  }

  @WebEndpoint(name="SecmanDasUsuarioPermisosPort")
  public mx.com.televisa.secman.view.permisos.SecmanDasUsuarioPermisos getSecmanDasUsuarioPermisosPort(WebServiceFeature... features)
  {
    return (mx.com.televisa.secman.view.permisos.SecmanDasUsuarioPermisos) super.getPort(new QName("http://webServices.view.secman.televisa.com.mx/",
                                                                                                               "SecmanDasUsuarioPermisosPort"),
                                                                                                     mx.com.televisa.secman.view.permisos.SecmanDasUsuarioPermisos.class,
                                                                                                     features);
  }
}
